[build]
builder = "NIXPACKS"
buildCommand = """
    python -m pip install -r requirements.txt && \
    python manage.py collectstatic --noinput && \
    python manage.py migrate && \
    python manage.py create_superuser_if_none_exists
"""

[deploy]
startCommand = "gunicorn steelgrid.wsgi:application"
healthcheckPath = "/"
healthcheckTimeout = 100
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3

[envs]
PYTHON_VERSION = "3.10.5"
DJANGO_SUPERUSER_USERNAME = "admin"
DJANGO_SUPERUSER_EMAIL = "admin@steelgridsystems.com"